{
 "title": "Application Télémetrie",
 "time": { "from": "2026-02-06T13:03:09.007Z", "to": "2026-02-06T16:03:39.021Z" },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rabbitmq_queue_messages{queue=\"admin-created\"}",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "nombre d'appel par seconde sur les 5 dernières minutes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kubekata_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nombre de pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=~\"kubekata-app|kubekata-worker\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application telemetrie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(kubekata_http_requests_total[1m])) by (action) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "(\n  sum(rate(kubekata_http_requests_total{status=~\"2..\"}[5m])) by (action)\n  / \n  sum(rate(kubekata_http_requests_total[5m])) by (action)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}